### ISSUE TITLE
Assertion Failure: removed (bf_tree.cpp:890)

### ISSUE THREAD

**Issue by PickXu** [caetanosauer/zero#33]
Hi,

When I get the clean zero repository on master branch, once I compiled, I ran this command:
./zapps kits -b tpcc -t 8 -q 16 --load --duration 300 --sm_bufpoolsize 32768 --crashDelay 120;

Then the system immediately crashes at the 890 line of bf_tree.cpp. Any suggestions on this?

Thanks.
Min

**Comment by caetanosauer** [comment]
Hi Min,

could you try passing --sm_format as well? Thanks!

**Comment by PickXu** [comment]
Hi Caetano,

It works.

Thanks.
Min

**Comment by caetanosauer** [comment]
Fixed in eda0923
